<?php

namespace App;

use App\Scopes\ScopeHostelImage;

class HostelImage extends Image
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ScopeHostelImage());
    }

    public function hostel()
    {
        return $this->belongsTo(Hostel::class);
    }
}
