<?php

namespace App;

use App\Scopes\ScopeReservation;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Reservation extends Selection
{
    const PRICING_RATE = 20;

    const ONGOING_RENTAL = 'ongoing';
    const UPCOMING_RENTAL = 'upcoming';
    const CLOSED_RENTAL = 'closed';

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope( new ScopeReservation());
    }



}
