<?php

namespace App;

use App\Scopes\ScopeRoomImage;
use Illuminate\Database\Eloquent\Model;

class RoomImage extends Image
{
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new ScopeRoomImage());
    }

    public function room()
    {
        return $this->belongsTo(Room::class);
    }
}
